### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by plitris** [aquto/cordova-plugin-imei#1]
I've used the function as in the example and it returns:
Cannot call method 'get' of undefined

**Comment by jrunge** [comment]
It's hard to tell exactly what the problem is without full code of your project, but there could be a few things wrong.

The plugin wasn't installed correctly, so you don't have the imei object attached to window.plugins.  Try removing and adding the plugin again through the command line.

You aren't waiting until after the "deviceready" event to make the call.  If you're calling window.plugins.imei.get when the app first launches, make sure whatever code initializes your app is being called from the deviceready event.
